[log]  
  reload = "reload config by %s"
  unban = "Player %s (uuid: %s) unbanned by %s"
  [log.whitelist]
    add = "added %s (uuid: %s) to whitelist by %s"
    remove = "removed %s (uuid: %s) from whitelist by %s"
    reload = "reload whitelist by %s"
    toggle = "%s toggle whitelist status to %s"
  [log.haproxy]
    toggle = "%s toggle haproxy status to %s"
[command]
  [command.help]
    whitelist_toggle = "&3/%s whitelist <on/off> &6- &bToggle whitelist status"
    whitelist_add = "&3/%s whitelist add <playername> &6- &bAdd player to whitelist"
    whitelist_remove = "&3/%s whitelist remove <playername> &6- &bRemove player from whitelist"
    whitelist_reload = "&3/%s whitelist reload &6- &breload whitelist"
    ban = "&3/%s ban <playername> [reason] &6- &bBan a player"
    tempban = "&3/%s tempban <playername> <time> [reason] &6- &bTemporarily ban a player"
    unban = "&3/%s unban <playername> &6- &bUnban a player"
    haproxy_toggle = "&3/%s haproxy <on/off> &6- &bToggle haproxy support"
    reload = "&3/%s reload &6- &breload config"
[messages]
  player_not_found = "&cPlayer %s not found"
  no_permission = "&cYou do not have permission"
  reload = "&aBungeeCordUserControl reloaded"
  [messages.whitelist]
    enable = "Whitelist enabled"
    disable = "Whitelist disabled"
    add = "&aAdded %s (uuid: %s) to whitelist"
    remove = "&aRemoved %s (uuid: %s) from whitelist"
    already_exists = "&cPlayer %s is already in whitelist"
    reload = "&awhitelist reloaded"
  [messages.login]
    whitelist = "&bYou are not whitelisted on this server"
    banned = "&bYou have been banned.\n &fReason: %s"
    tempban = "&bYou have been temporarily banned.\n &fReason: %s\n &fEnd in: %s"
    reload = "&bBUC is reloading"
  [messages.ban]
    success = "&aPlayer %s banned "
    already_banned = "&cPlayer %s is already banned"
  [messages.tempban]
    time_invalid = "&cTime is invalid"
  [messages.unban]
    success = "&aPlayer %s unbanned"
    not_banned = "&cPlayer %s is not banned"
  [messages.haproxy]
    enable = "haproxy support enabled"
    disable = "haproxy support disabled"